import localFont from "next/font/local";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Sidebar } from "@/Components/sidebar/Sidebar";
import { Header } from "@/Components/header/Header";
import { Theme } from "@radix-ui/themes";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`flex h-screen overflow-hidden`}
      >

        {/* ===== Sidebar Start ===== */}
        {/* <SideBarAnt /> */}
        <div className="w-[100px]">
          <Sidebar />
        </div>
        {/* ===== Sidebar End ===== */}

        {/* ===== Content Area Start ===== */}
        <div className="relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden">
          {/* ===== Header Start ===== */}
          {/* ===== Header End ===== */}
          {/* ===== Main Content Start ===== */}
          <main className="relative">
            <div className="mx-auto max-w-screen-2xl px-4 md:px-6 2xl:px-10">
              {children}
            </div>
          </main>
          {/* ===== Main Content End ===== */}
        </div>
        {/* ===== Content Area End ===== */}
      </body>
    </html>
  );
}
